In [2]:
import numpy as np

Create a null vector of size 10 but the fifth value which is 1

In [3]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Reverse a vector

In [4]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [7]:
Z = np.random.random((3,3,3))

print(Z)
print(Z.shape)

[[[0.24245235 0.04535183 0.55718822]
  [0.44218298 0.73078293 0.23086559]
  [0.60694265 0.88742748 0.79973793]]

 [[0.0673828  0.13468967 0.79730299]
  [0.94873705 0.00132593 0.66330313]
  [0.25831638 0.76586561 0.77212986]]

 [[0.21204974 0.4945131  0.97733942]
  [0.12811176 0.2437648  0.77996992]
  [0.64211157 0.04994048 0.60735071]]]
(3, 3, 3)


Create a 10x10 array with random values and find the minimum and maximum values

In [8]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.006104993871629105 0.992908615648541


Create a random vector of size 30 and find the mean value

In [9]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5360057137291896


Create a 2d array with 1 on the border and 0 inside

In [10]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


How to add a border (filled with 0's) around an existing array?

In [11]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [12]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [14]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Create a 8x8 matrix and fill it with a checkerboard pattern

In [15]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [17]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Normalize a 5x5 random matrix

In [18]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-7.71731269e-01 -4.08884377e-01  8.06947292e-01  1.19201933e+00
   1.03673693e+00]
 [-1.03624923e+00 -9.05506697e-01  3.24802361e-01  1.59320104e-03
  -4.31535788e-01]
 [-1.98070688e+00  1.22334471e+00  9.72224150e-01  1.19485722e+00
   1.13885074e+00]
 [ 9.99184336e-01  2.66588221e-01 -1.56029324e+00  1.17923557e-01
  -6.29517100e-01]
 [ 5.19094641e-01  1.25750312e+00 -6.50559509e-01 -1.48790492e+00
  -1.18878080e+00]]


Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [19]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z.shape)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z.shape)

(5, 2)
(5, 2)


In [20]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [21]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [23]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Asus\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\Asus\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


How to round away from zero a float array ?

In [24]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[  5.  -9.  -6.   9.   8. -10.  -9.   3.   5.  -7.]


How to find common values between two arrays?

In [25]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

print(Z1)
print(Z2)
print(np.intersect1d(Z1,Z2))

[0 2 1 4 4 7 6 0 2 4]
[0 9 4 9 1 1 0 9 1 0]
[0 1 4]


In [27]:
Z = np.random.random(10)
Z.sort()
print(Z*100)

[13.62328497 26.33764228 26.36725649 28.09222832 62.80552603 66.29545041
 70.11069423 80.93772631 85.7407266  85.88633506]


In [29]:
# How to sum a small array faster than np.sum?
Z = np.arange(10)
np.add.reduce(Z)

45